from __future__ import annotations
import uuid
import logging
from typing import Dict, Any, List
from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel

from app.agents.framework import EventBus
from app.agents.orchestrator_agent import OrchestratorAgent
from app.core import database
from app.services.case_store import CaseStore
from app.api.v1.security import require_api_key

router = APIRouter(prefix="/api/v1/agents", tags=["agents"])
logger = logging.getLogger(__name__)

class AgentAnalyzeRequest(BaseModel):
    transaction_id: str | None = None
    account_id: str
    transaction_amount: float
    upi_id: str | None = None
    upi_name: str | None = None
    narrative: str | None = None
    timestamp: str | None = None

class CaseStatusUpdateRequest(BaseModel):
    status: str

@router.post("/analyze")
async def analyze_transaction(
    payload: AgentAnalyzeRequest,
    _: None = Depends(require_api_key)
) -> Dict[str, Any]:
    """Runs a complete multi-agent analysis on a transaction, persisting the results."""
    try:
        event_bus = EventBus()
        orchestrator = OrchestratorAgent(event_bus)
        
        # Build the context dictionary
        context = {
            "transaction_id": payload.transaction_id or f"TXN_{uuid.uuid4().hex[:10]}",
            "account_id": payload.account_id,
            "transaction_amount": payload.transaction_amount,
            "upi_id": payload.upi_id or "unknown",
            "upi_name": payload.upi_name or "unknown",
            "narrative": payload.narrative or "",
            "timestamp": payload.timestamp or database.datetime.now(database.UTC).isoformat()
        }
        
        result = await orchestrator.analyze(context)
        
        return {
            "status": "success",
            "run_id": result.metadata.get("run_id"),
            "final_score": result.score,
            "final_decision": result.decision,
            "reasoning": result.reasoning,
            "timeline": result.metadata.get("timeline"),
            "messages": result.metadata.get("messages"),
            "agent_results": result.metadata.get("agent_results")
        }
    except Exception as e:
        logger.error(f"Error executing agentic analysis: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/decisions")
async def list_decisions(
    limit: int = 50,
    _: None = Depends(require_api_key)
) -> List[Dict[str, Any]]:
    """Lists recent orchestration runs and agent decisions."""
    try:
        return database.get_orchestration_runs(limit)
    except Exception as e:
        logger.error(f"Error fetching decisions: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/run/{run_id}")
async def get_run_details(
    run_id: str,
    _: None = Depends(require_api_key)
) -> Dict[str, Any]:
    """Fetches details for a specific multi-agent analysis run."""
    try:
        run = database.get_orchestration_run(run_id)
        if not run:
            raise HTTPException(status_code=404, detail="Run not found")
        return run
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error fetching run details for {run_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/timeline/{run_id}")
async def get_timeline(
    run_id: str,
    _: None = Depends(require_api_key)
) -> Dict[str, Any]:
    """Gets the timeline log and communications for an orchestration run."""
    try:
        run = database.get_orchestration_run(run_id)
        if not run:
            raise HTTPException(status_code=404, detail="Run not found")
        return {
            "run_id": run_id,
            "timeline": run.get("timeline", []),
            "messages": run.get("messages", [])
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error fetching timeline for {run_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/cases")
async def list_cases(
    limit: int = 50,
    _: None = Depends(require_api_key)
) -> List[Dict[str, Any]]:
    """Lists compliance cases generated by agent escalations."""
    try:
        store = CaseStore()
        return store.list_recent(limit)
    except Exception as e:
        logger.error(f"Error listing cases: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/cases/{case_id}/status")
async def update_case_status(
    case_id: str,
    payload: CaseStatusUpdateRequest,
    _: None = Depends(require_api_key)
) -> Dict[str, Any]:
    """Updates the workflow status of an active case."""
    try:
        store = CaseStore()
        updated = store.update(case_id, {"status": payload.status})
        if not updated:
            raise HTTPException(status_code=404, detail="Case not found")
        return {"status": "success", "case": updated}
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error updating case status for {case_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))
